#!/bin/bash

PHONEBOOK_ENTRIES="bash_phonebook_entries"

if [ "$#" -lt 1 ]; then
    exit 1

elif [ "$1" = "new" ]; then
    # YOUR CODE HERE #
    echo -e "$2\t$3" >> "$PHONEBOOK_ENTRIES"

elif [ "$1" = "list" ]; then
    if [ ! -e "$PHONEBOOK_ENTRIES" ] || [ ! -s "$PHONEBOOK_ENTRIES" ]; then
        echo "phonebook is empty"
    else
        # YOUR CODE HERE #
	cat "$PHONEBOOK_ENTRIES" | tr "\t" " "
    fi

elif [ "$1" = "lookup" ]; then
    # YOUR CODE HERE #
    grep -F "$2" "$PHONEBOOK_ENTRIES" | while IFS=$'\t' read -r name number; do
        if [ "$name" = "$2" ]; then 
	   echo "$number"
   	fi	   
    done
    

elif [ "$1" = "remove" ]; then
    # YOUR CODE HERE #
    grep -v -F "$2" "$PHONEBOOK_ENTRIES" | while IFS=$'\t' read -r line; do
    	echo "$line" >> "$PHONEBOOK_ENTRIES.txt"
    done

    mv "$PHONEBOOK_ENTRIES.txt" "$PHONEBOOK_ENTRIES"


elif [ "$1" = "clear" ]; then
    # YOUR CODE HERE #
    > "$PHONEBOOK_ENTRIES"
else
     # YOUR CODE HERE #
     echo "unknown command!"
fi
